# fly.toml app configuration file generated for autumn-wind-2065 on 2023-06-06T13:51:02+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "autumn-wind-2065"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
